"""refactoring

Revision ID: 7794b47b60b5
Revises: f5743d63c318
Create Date: 2026-01-15 09:01:04.837402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7794b47b60b5'
down_revision: Union[str, Sequence[str], None] = 'f5743d63c318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_price_ticker'), table_name='ticker_price')
    op.create_index(op.f('ix_ticker_price_ticker'), 'ticker_price', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_price_ticker'), table_name='ticker_price')
    op.create_index(op.f('ix_ticker_price_ticker'), 'ticker_price', ['ticker'], unique=True)
    # ### end Alembic commands ###
